name: deploy-master

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: my-angular-website
      AWS_ACCESS_KEY_ID: ${{ secrets.MASTER_AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MASTER_AWS_SECRET }}
      AWS_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Angular CLI
        run: npm install -g @angular/cli@14
      - name: Install Dependencies
        run: npm install --force
      - name: Build Angular App
        run: node --max_old_space_size=12192 ./node_modules/@angular/cli/bin/ng build --progress false --configuration=production
      

      - name: Clean Default S3 Bucket
        run: aws s3 rm s3://${{ vars.MASTER_BUCKET_NAME }} --recursive
      - name: Upload Build Files to Default S3 Bucket
        run: aws s3 cp dist/${{ env.APP_NAME }}/ s3://${{ vars.MASTER_BUCKET_NAME }} --recursive
      - name: Upload Apple Icons to Default S3 Bucket
        run: aws s3 cp dist/${{ env.APP_NAME }}/assets/pwa-icons/ios/ s3://${{ vars.MASTER_BUCKET_NAME }} --recursive
      - name: Create CloudFront Cache Invalidation for Main Distribution
        run: AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${{ vars.MASTER_CLOUDFRONT_ID }}  --paths "/*"